[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  PNPM_VERSION = "8.6.0"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["bcryptjs"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".next/server/pages/api"
